// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgmCNwtbg6LCgV6w2HY-Qf3KlhSBw6wZs',
    appId: '1:650032257006:web:3a8e1ccb10600de8b520ff',
    messagingSenderId: '650032257006',
    projectId: 'swd392-f262d',
    authDomain: 'swd392-f262d.firebaseapp.com',
    storageBucket: 'swd392-f262d.firebasestorage.app',
    measurementId: 'G-FQ7S5VR2JE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrwSPtHcxX0UAYx6GmYJcEvZZROCoyl9k',
    appId: '1:650032257006:android:c9cbaf196c557d42b520ff',
    messagingSenderId: '650032257006',
    projectId: 'swd392-f262d',
    storageBucket: 'swd392-f262d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANz9DA5e25UW2rrlSU-hLsW4DW4kMxGPc',
    appId: '1:650032257006:ios:941cb9f16ac21067b520ff',
    messagingSenderId: '650032257006',
    projectId: 'swd392-f262d',
    storageBucket: 'swd392-f262d.firebasestorage.app',
    iosClientId: '650032257006-ie4sus8f8rqjgj00n2dgukhqs41b5s2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectAuthen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANz9DA5e25UW2rrlSU-hLsW4DW4kMxGPc',
    appId: '1:650032257006:ios:941cb9f16ac21067b520ff',
    messagingSenderId: '650032257006',
    projectId: 'swd392-f262d',
    storageBucket: 'swd392-f262d.firebasestorage.app',
    iosClientId: '650032257006-ie4sus8f8rqjgj00n2dgukhqs41b5s2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectAuthen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgmCNwtbg6LCgV6w2HY-Qf3KlhSBw6wZs',
    appId: '1:650032257006:web:960b6011ccc9fce4b520ff',
    messagingSenderId: '650032257006',
    projectId: 'swd392-f262d',
    authDomain: 'swd392-f262d.firebaseapp.com',
    storageBucket: 'swd392-f262d.firebasestorage.app',
    measurementId: 'G-CQKJL4WTN9',
  );

}